version: '3'
services:
  db:
    image: 'postgres:latest'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: urlshortener
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  app:
    container_name: ChallengeEncurtador-api
    restart: always
    build: .
    ports: 
      - "8081:8081"
    networks:
      - desafio-docker-network
    depends_on: 
      - db

networks:
  desafio-docker-network:
    driver: bridge